INSERT INTO dishes(name, description, price, available, categoryid, countryid)
VALUES('Jollof rice with chicken or beef', 'A delicious Ghanain dish of seasoned rice with chicken or beef.', '46.00', 10, 6, 4 ),
('Waakye with fried chicken or fish', 'Ghanaian dish of seasoned rice and beans, served with fried chicken or fish.', '41.48', 10, 6, 4 ),
('Banku with grilled tilapia', 'A traditional Ghanaian dish consisting of fermented corn and cassava dough, typically served with grilled tilapia fish for a flavorful and satisfying meal.', '34.00', 10, 6, 4 ),
('Fufu with goat meat soup', 'A classic Ghanain meal of pounded dough served with goat meat soup.', '14.00', 10, 6, 4 ),
('Kelewele with grilled pork', 'Ghanaian street food combo of spicy fried plantains and grilled pork.', '44.00', 10, 6, 4 ),
('Red-red with fried plantains and fish', 'A Ghanaian dish featuring fried plantains and fish served with a rich and spicy bean stew, creating a flavorful and satisfying meal.', '44.00', 10, 6, 4 ),
('Tuo Zaafi with beef or chicken stew', 'A Ghanaian dish consisting of pounded yam balls served with a flavorful beef or chicken stew, creating a hearty and delicious meal.', '40.00', 10, 6, 4 ),
('Ampesi with kontomire stew and fish', 'Ghanaian meal featuring boiled yam, plantains, cassava, kontomire stew, and fish.', '14.99', 10, 6, 4 ),
('Omo tuo with groundnut soup and chicken', 'A Ghanaian dish consisting of rice balls served with a flavorful peanut soup and chicken, creating a delicious and comforting meal.', '43.99', 10, 6, 4 ),
('Kenkey with fried fish and pepper sauce', 'A Ghanaian dish featuring fermented corn dough (kenkey) served with fried fish and spicy pepper sauce, offering a delicious and satisfying meal.', '21.99', 10, 6, 4 ),